apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: dev
resources:
  - ../base

images:
  - name: ghcr.io/stefanprodan/podinfo
    newTag: 6.6.0

patches:
  - target:
      kind: Ingress
      name: podinfo
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: podinfo.dev.local
